// <auto-generated />
using System;
using HomeCloud.Drive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeCloud.Drive.Data.Migrations
{
    [DbContext(typeof(DriveDbContext))]
    [Migration("20191229144145_addRel1")]
    partial class addRel1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeCloud.Drive.Core.Entities.DirectoryDescriptor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentDirectoryDescryptorId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentDirectoryDescryptorId");

                    b.ToTable("DirectoryDescriptors");
                });

            modelBuilder.Entity("HomeCloud.Drive.Core.Entities.FileDescriptor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DirectoryDescriptorId")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryDescriptorId");

                    b.ToTable("FileDescriptors");
                });

            modelBuilder.Entity("HomeCloud.Drive.Core.Entities.DirectoryDescriptor", b =>
                {
                    b.HasOne("HomeCloud.Drive.Core.Entities.DirectoryDescriptor", "ParentDirectoryDescryptor")
                        .WithMany("ChildDirectoryDescryptors")
                        .HasForeignKey("ParentDirectoryDescryptorId");
                });

            modelBuilder.Entity("HomeCloud.Drive.Core.Entities.FileDescriptor", b =>
                {
                    b.HasOne("HomeCloud.Drive.Core.Entities.DirectoryDescriptor", "DirectoryDescriptor")
                        .WithMany("FileDescriptors")
                        .HasForeignKey("DirectoryDescriptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
